---
- name: Update RHEL
  hosts: RHEL8a
  become: yes
  gather_facts: yes

  tasks:
    - name: Print Software Version
      command: cat /etc/redhat-release

    - name: Update Packages
      yum:
        name: '*'
        state: latest
