---
- name: VMware Create Virtual Machine
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create virtual machine
      community.vmware.vmware_guest:
        datacenter: "{{ vmware_datacenter }}"
        cluster: "{{ vmware_cluster }}"
        folder: "/{{ vmware_datacenter }}/vm"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        state: poweredon
        disk:
        - size_gb: "{{ disk_size }}"
          type: thin
          datastore: "{{ vmware_datastore }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
        - name: "{{ vm_network }}"
          ip: "{{ vm_ip }}"
          netmask: "{{ vm_network_netmask }}"
          gateway: "{{ vm_network_gateway }}"
          domain: "{{ network_domain }}"
          dns_servers: "{{ vm_dns_server }}"
        wait_for_ip_address: yes
        customization:
          autologon: true
          autologoncount: 1
          dns_servers:
          - "{{ vm_dns_server }}"
          domain: "{{ network_domain }}"
          password: '{{ vm_password }}'
