---
#
# TWGCB-01-008-0040
#

# check step
# 1. check boot files password
- name: initial variables
  set_fact:
    var_status: "{{ (rule_status == commons.check_mode.by_pass) | ternary(commons.check_status.by_pass, '') }}"
    var_result: "{{ (rule_status == commons.check_mode.by_pass) | ternary('N/A', '') }}"

# - debug:
#     msg: "{{ rule_id + ':' + rule_status + ':' + var_status + ':' + var_result }}"

- name: check block
  block:
    - name: check boot files password
      shell: >
        if [ -d "/sys/firmware/efi" ]; then
          if [[ $(grep '^GRUB2_PASSWORD' /boot/efi/EFI/redhat/user.cfg) != "" ]]; then
            echo "PASS => /boot/efi/EFI/redhat/grub2/user.cfg => check GRUB2_PASSWORD"
          else
            echo "FAILED => /boot/efi/EFI/redhat/grub2/user.cfg => check GRUB2_PASSWORD"
          fi
        else
          if [[ $(grep '^GRUB2_PASSWORD' /boot/grub2/user.cfg) != "" ]]; then
            echo "PASS => /boot/grub2/user.cfg => check GRUB2_PASSWORD"
          else
            echo "FAILED => /boot/grub2/user.cfg => check GRUB2_PASSWORD"
          fi
        fi
      register: result
      ignore_errors: true

    - debug:
        var: result

    - name: parse result - PASS
      set_fact:
        var_status: "{{ commons.check_status.pass }}"
        var_result: "{{ result.stdout }}"
      when: 
        - result is defined
        - result.rc == 0
    
    - name: parse result - FAIL
      set_fact:
        var_status: "{{ commons.check_status.fail }}"
        var_result: "{{ result.stdout }}"
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout.find("FAILED") != -1

    # - debug:
    #     msg: "after in {{ rule_id + ':' + var_status + ':' + var_result }}"

  when:
    - rule_status == commons.check_mode.do_check

# - debug:
#     msg: "after {{ rule_id + ':' + var_status + ':' + var_result }}"

- name: Pass check results to role
  include_role:
    name: util/check/update_result
  vars:
    rule_status: "{{ var_status }}"
    rule_result: "{{ var_result }}"
...