---
#
# TWGCB-01-008-0070
#

# check step
# 1. check lib owner
- name: initial variables
  set_fact:
    var_status: "{{ (rule_status == commons.check_mode.by_pass) | ternary(commons.check_status.by_pass, '') }}"
    var_result: "{{ (rule_status == commons.check_mode.by_pass) | ternary('N/A', '') }}"

# - debug:
#     msg: "{{ rule_id + ':' + rule_status + ':' + var_status + ':' + var_result }}"

- name: check block
  block:
    - name: check lib owner
      shell: >
        if [[ $(find -L /lib /lib64 /usr/lib /usr/lib64 ! -user root) != "" ]]; then
          find -L /lib /lib64 /usr/lib /usr/lib64 ! -user root | while read file; do
            fileperm=$(ls -la $file | cut -f1 -d" ")
            if [ $(echo $fileperm | cut -c1) != "l" ]; then
              ls -al $file
            fi
          done
        fi
      register: result
      ignore_errors: true

    - debug:
        var: result

    - name: parse result - PASS
      set_fact:
        var_status: "{{ commons.check_status.pass }}"
        var_result: |
          PASS => all lib files owned by user root
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout | default('', true) | trim == ""
    
    - name: parse result - FAIL
      set_fact:
        var_status: "{{ commons.check_status.fail }}"
        var_result: |
          FAILED => found file owner not root.
          {{ result.stdout }}
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout | default('', true) | trim != ""

    # - debug:
    #     msg: "after in {{ rule_id + ':' + var_status + ':' + var_result }}"

  when:
    - rule_status == commons.check_mode.do_check

# - debug:
#     msg: "after {{ rule_id + ':' + var_status + ':' + var_result }}"

- name: Pass check results to role
  include_role:
    name: util/check/update_result
  vars:
    rule_status: "{{ var_status }}"
    rule_result: "{{ var_result }}"
...