---
#
# TWGCB-01-008-0044
#

# check step
# 1. check crypto policy
- name: initial variables
  set_fact:
    var_status: "{{ (rule_status == commons.check_mode.by_pass) | ternary(commons.check_status.by_pass, '') }}"
    var_result: "{{ (rule_status == commons.check_mode.by_pass) | ternary('N/A', '') }}"

# - debug:
#     msg: "{{ rule_id + ':' + rule_status + ':' + var_status + ':' + var_result }}"

- name: check block
  block:
    - name: check crypto policy
      shell: >
        cpolicy=$(update-crypto-policies --show);
        if [ $cpolicy == "FUTURE" ] || [ $cpolicy == "FIPS" ]; then
          echo "crypto policy is $cpolicy"
        else
          echo "crypto policy is $cpolicy, not FUTURE or FIPS"
        fi
      register: result
      ignore_errors: true

    - debug:
        var: result

    - name: parse result - PASS
      set_fact:
        var_status: "{{ commons.check_status.pass }}"
        var_result: |
          PASS => {{ result.stdout }}
      when: 
        - result is defined
        - result.rc == 0
    
    - name: parse result - FAIL
      set_fact:
        var_status: "{{ commons.check_status.fail }}"
        var_result: |
          FAILED => {{ result.stdout }}
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout.find("not") != -1

    # - debug:
    #     msg: "after in {{ rule_id + ':' + var_status + ':' + var_result }}"

  when:
    - rule_status == commons.check_mode.do_check

# - debug:
#     msg: "after {{ rule_id + ':' + var_status + ':' + var_result }}"

- name: Pass check results to role
  include_role:
    name: util/check/update_result
  vars:
    rule_status: "{{ var_status }}"
    rule_result: "{{ var_result }}"
...