---
#
# TWGCB-01-008-0082
#

# check step
# 1. check . file
- name: initial variables
  set_fact:
    var_status: "{{ (rule_status == commons.check_mode.by_pass) | ternary(commons.check_status.by_pass, '') }}"
    var_result: "{{ (rule_status == commons.check_mode.by_pass) | ternary('N/A', '') }}"

# - debug:
#     msg: "{{ rule_id + ':' + rule_status + ':' + var_status + ':' + var_result }}"

- name: check block
  block:
    - name: check . file
      shell: >
        grep -E -v '^(halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "'"$(which nologin)"'" && $7 != "/bin/false" && $3 >= 1000 && $1 != "nobody") { print $1 " " $6 }' | while read user dir; do
          if [ ! -d "$dir" ]; then
            echo "The home directory ($dir) of user $user does not exist."
          else
            dirperm=$(ls -ld $dir | cut -f1 -d" ")
            if [ $(echo $dirperm | cut -c5) != "-" ]; then
              echo "Group Read permission set on the home directory ($dir) of user $user"
            fi
            if [ $(echo $dirperm | cut -c6) != "-" ]; then
              echo "Group Write permission set on the home directory ($dir) of user $user"
            fi
            if [ $(echo $dirperm | cut -c7) != "-" ]; then
              echo "Group Execute permission set on the home directory ($dir) of user $user"
            fi
            if [ $(echo $dirperm | cut -c8) != "-" ]; then
              echo "Other Read permission set on the home directory ($dir) of user $user"
            fi
            if [ $(echo $dirperm | cut -c9) != "-" ]; then
              echo "Other Write permission set on the home directory ($dir) of user $user"
            fi
            if [ $(echo $dirperm | cut -c10) != "-" ]; then
              echo "Other Execute permission set on the home directory ($dir) of user $user"
            fi
          fi
        done
      register: result
      ignore_errors: true

    - debug:
        var: result

    - name: parse result - PASS
      set_fact:
        var_status: "{{ commons.check_status.pass }}"
        var_result: |
          PASS => no file with goupr or other write permission found.
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout | default('', true) | trim == ""
    
    - name: parse result - FAIL
      set_fact:
        var_status: "{{ commons.check_status.fail }}"
        var_result: |
          FAILED =>
          {{ result.stdout }}
      when: 
        - result is defined
        - result.rc == 0
        - result.stdout | default('', true) | trim != ""

    # - debug:
    #     msg: "after in {{ rule_id + ':' + var_status + ':' + var_result }}"

  when:
    - rule_status == commons.check_mode.do_check

# - debug:
#     msg: "after {{ rule_id + ':' + var_status + ':' + var_result }}"

- name: Pass check results to role
  include_role:
    name: util/check/update_result
  vars:
    rule_status: "{{ var_status }}"
    rule_result: "{{ var_result }}"
...