---
#################################################
#
# code : fix.yaml
# function : fix RHEL 8 by TWGCB rules
# author : Frank Lin (frank.lin@redhat.com)
# version : 0.1
# update : 2022/08/18
#
#################################################

### task part
- hosts: all
  gather_facts: true
  become: true
  tasks:
    # Apply TWGCB-01-008-0129 Rule
    - name: change directory permissions
      copy: src=./disable_tipc.sh dest=./disable_tipc.sh mode=0775
    
    - name: Change modprobe tipc disabled
      command: sh ./disable_tipc.sh

    # Apply TWGCB-01-008-0130 Rule
    - name: Download Apache tarball file
      shell: nmcli radio wifi off
	  
    # Apply TWGCB-01-008-0131 Rule 
    - name: Change interface promisc mode disabled
      shell: promisc off
    