---
- hosts: all
  gather_facts: no
  
  tasks:
  #Prepare
  - name: Config ens192 1
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: "^check_link_down.*"
      line: 'DNS1=8.8.8.8'
  - name: Config ens192 2
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: ' return 1;'
      line: ''
  - name: Config ens192 3
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '}'
      line: ''
  - name: Reboot
    reboot:
  - name: Subscription
    command: "subscription-manager register --username=carenchu --password=1qazXDR% --auto-attach --force"
  - name: Update
    command: "yum update -y"
  - name: Install podman
    command: "yum install -y podman"

