---
# tasks file for update_result
- name: set result to check_status and check_results dictionary variables
  set_fact:
    check_status:  "{{ check_status  | default({}) | combine({ rule_id : rule_status }) }}"
    check_results: "{{ check_results | default({}) | combine({ rule_id : rule_result }) }}"

# - debug:
#     var: check_status
- debug:
    var: check_results
...