---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "IP_ADDRESS"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "PASSWORD"
    datacenter_name: "Datacenter"
    cluster_name: "cluster"
    datastore: "XXXXXX-XX"
  tasks:
  - name: Remove Snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter: "{{ datacenter_name }}"
      folder: /Leon/DEV
      name: "{{ item }}"
      state: absent
      snapshot_name: "{{ snapshot_name }}"
#      snapshot_name: snapshot_name
      description: snapshot_description
      validate_certs: no
    loop:
      - DEV01
      - DEV02